import os
import json
import logging
import requests
from datetime import datetime, timezone
from decimal import Decimal
from typing import Dict, Any, Optional
from fastapi import HTTPException, status
from sqlalchemy.orm import Session
from sqlalchemy import func

from src.core.config import get_settings
from src.models.quotation import Quotation, QuoteLine
from src.models.deal import Deal
from src.models.customer import Customer, CustomerTier
from src.models.billing import Subscription, SubscriptionPlan, Invoice
from src.models.product import Product
from src.models.ai_config import CompanyAIConfig
from src.models.approval import ApprovalRequest, ApprovalAuditLog
from src.models.portal import QuoteMessage
from src.models.operations import Stock, Warehouse, Order, FulfillmentAllocation, Backorder
from src.services.fulfillment_service import generate_fulfillment_plans
from src.services.shipping_service import shipping_service

logger = logging.getLogger(__name__)

WAREHOUSE_SYSTEM_PROMPT_TEMPLATE = """You are a DealFlow360 fulfillment decision-support assistant.

Use only the warehouse, stock, shipping and fulfillment facts supplied.

Do not invent stock.

Do not create new allocations.

Do not invent shipping costs or ETA.

Compare only the fulfillment plans generated by DealFlow360.

Explain the trade-offs between cost, speed, shipment count, stock utilization, backorder risk and margin.

The backend is authoritative.

Return a JSON object structured as follows:
{
  "summary": "...",
  "fulfillment_analysis": "...",
  "stock_utilization_observation": "...",
  "shipping_cost_tradeoff": "...",
  "backorder_risk_observation": "...",
  "recommended_plan_id": "...",
  "explanation_details": "...",
  "tradeoffs": ["..."],
  "recommendations": ["..."]
}"""

AI_SYSTEM_PROMPT_TEMPLATE = """You are DealFlow360's internal quotation decision-support assistant.

Use ONLY the facts supplied in the backend context.

Never invent customer information, prices, discounts, margins, inventory, shipping rates, approval states, or business events.

If information is missing, explicitly say that it is unavailable.

Backend calculations and business rules are authoritative.

Your output is advisory and must never override DealFlow360 business rules.

Role Perspective: {role_perspective}

Explain the current quotation in the context of the customer's historical relationship with the company.

Return a JSON object structured as follows:
{{
  "summary": "...",
  "customer_context": "...",
  "quotation_analysis": "...",
  "loyalty_observation": "...",
  "subscription_observation": "...",
  "purchase_behavior": "...",
  "discount_observation": "...",
  "margin_observation": "...",
  "approval_observation": "...",
  "fulfillment_observation": "...",
  "shipping_observation": "...",
  "risks": ["..."],
  "opportunities": ["..."],
  "recommendations": ["..."]
}}"""

def json_serialize_default(obj):
    if isinstance(obj, Decimal):
        return float(obj)
    if hasattr(obj, "isoformat"):
        return obj.isoformat()
    return str(obj)

class AIService:
    def __init__(self):
        settings = get_settings()
        self.enabled = os.environ.get("AI_ENABLED", str(settings.AI_ENABLED)).lower() == "true"
        self.provider = os.environ.get("AI_PROVIDER", settings.AI_PROVIDER)
        self.base_url = os.environ.get("AI_BASE_URL", settings.AI_BASE_URL)
        self.model = os.environ.get("AI_MODEL", settings.AI_MODEL)

    def build_quotation_ai_context(self, db: Session, quotation_id: str) -> Dict[str, Any]:
        """
        Loads authoritative dynamic facts from PostgreSQL for a given quotation.
        """
        quotation = db.query(Quotation).filter(Quotation.id == quotation_id).first()
        if not quotation:
            return {}

        deal = db.query(Deal).filter(Deal.id == quotation.deal_id).first()
        customer = db.query(Customer).filter(Customer.name == deal.customer_name).first() if deal else None
        tier = db.query(CustomerTier).filter(CustomerTier.id == customer.tier_id).first() if customer and customer.tier_id else None

        # ── 1. CUSTOMER FACTS ──────────────────────────────────────────────────
        lifetime_revenue = 0.0
        purchase_count = 0
        avg_order_value = 0.0
        last_purchase_date = "N/A"
        historical_avg_discount = 0.0
        account_creation_date = "N/A"
        account_age_days = "N/A"
        previous_quotes_summary = []
        previous_deals_summary = []
        previous_orders_summary = []

        if customer:
            if customer.created_at:
                account_creation_date = customer.created_at.isoformat()
                now_utc = datetime.now(timezone.utc)
                c_created = customer.created_at if customer.created_at.tzinfo else customer.created_at.replace(tzinfo=timezone.utc)
                account_age_days = (now_utc - c_created).days

            invoices = db.query(Invoice).filter(Invoice.customer_id == customer.id).all()
            purchase_count = len(invoices)
            if invoices:
                lifetime_revenue = sum(inv.total for inv in invoices)
                avg_order_value = round((lifetime_revenue / purchase_count), 2) if purchase_count > 0 else 0.0
                sorted_invs = sorted(invoices, key=lambda x: x.created_at or datetime.min, reverse=True)
                if sorted_invs and sorted_invs[0].created_at:
                    last_purchase_date = sorted_invs[0].created_at.isoformat()
                for inv in invoices[:5]:
                    previous_orders_summary.append({
                        "invoice_id": inv.id,
                        "total": inv.total,
                        "status": inv.status,
                        "date": inv.created_at.isoformat() if inv.created_at else "N/A"
                    })

            cust_deals = db.query(Deal).filter(Deal.customer_name == customer.name).all()
            for d in cust_deals:
                previous_deals_summary.append({
                    "deal_id": d.id,
                    "value": d.value,
                    "status": d.status,
                    "risk": d.risk
                })

            deal_ids = [d.id for d in cust_deals]
            if deal_ids:
                past_quotes = db.query(Quotation).filter(Quotation.deal_id.in_(deal_ids)).all()
                for q_past in past_quotes:
                    disc_pct = round((q_past.total_discount / q_past.subtotal * 100.0), 2) if q_past.subtotal > 0 else 0.0
                    previous_quotes_summary.append({
                        "quotation_id": q_past.id,
                        "total": q_past.total,
                        "status": q_past.status,
                        "discount_percentage": disc_pct
                    })
                if past_quotes:
                    disc_sum = sum(q_past.total_discount for q_past in past_quotes if q_past.subtotal > 0)
                    sub_sum = sum(q_past.subtotal for q_past in past_quotes if q_past.subtotal > 0)
                    historical_avg_discount = round((disc_sum / sub_sum * 100.0), 2) if sub_sum > 0 else 0.0

        # ── 2. SUBSCRIPTIONS ───────────────────────────────────────────────────
        subscriptions_data = []
        if customer:
            subs = db.query(Subscription).filter(Subscription.customer_id == customer.id).all()
            for s in subs:
                p = db.query(SubscriptionPlan).filter(SubscriptionPlan.id == s.plan_id).first()
                subscriptions_data.append({
                    "subscription_id": s.id,
                    "plan_name": p.name if p else "Plan",
                    "subscription_type": p.billing_cycle if p else "monthly",
                    "subscription_value": p.price if p else 0.0,
                    "status": s.status,
                    "start_date": s.start_date.isoformat() if s.start_date else "N/A",
                    "renewal_date": s.end_date.isoformat() if hasattr(s, "end_date") and s.end_date else "Auto-renews monthly"
                })

        # ── 3. QUOTATION & LINES ───────────────────────────────────────────────
        line_items = []
        total_cost = 0.0
        for line in quotation.lines:
            product = db.query(Product).filter(Product.id == line.product_id).first()
            unit_cost = product.unit_cost if product and hasattr(product, "unit_cost") and product.unit_cost is not None else round(line.unit_price * 0.7, 2)
            line_subtotal = round(line.quantity * line.unit_price, 2)
            line_discount_amount = round(line_subtotal * (line.discount_percent / 100.0), 2)
            line_total = round(line_subtotal - line_discount_amount, 2)
            line_cost = round(line.quantity * unit_cost, 2)
            line_margin = round(line_total - line_cost, 2)
            line_margin_pct = round((line_margin / line_total * 100.0), 2) if line_total > 0 else 0.0
            total_cost += line_cost

            line_items.append({
                "line_id": line.id,
                "product_id": line.product_id,
                "product_name": product.name if product else "Product",
                "sku": product.sku if product else "SKU",
                "category": product.category if product and hasattr(product, "category") else "General",
                "quantity": line.quantity,
                "unit_price": line.unit_price,
                "unit_cost": unit_cost,
                "discount_percent": line.discount_percent,
                "line_subtotal": line_subtotal,
                "line_total_amount": line_total,
                "line_margin": line_margin,
                "line_margin_percentage": line_margin_pct
            })

        total_margin = round(quotation.total - total_cost, 2)
        total_discount_pct = round((quotation.total_discount / quotation.subtotal * 100.0), 2) if quotation.subtotal > 0 else 0.0

        # ── 4. APPROVAL CONTEXT ────────────────────────────────────────────────
        app_req = db.query(ApprovalRequest).filter(ApprovalRequest.quotation_id == quotation.id).order_by(ApprovalRequest.created_at.desc()).first()
        approval_logs_data = []
        rejection_reason = "None"
        if app_req:
            logs = db.query(ApprovalAuditLog).filter(ApprovalAuditLog.approval_request_id == app_req.id).all()
            for l in logs:
                approval_logs_data.append({
                    "actor_id": l.actor_id,
                    "action": l.action,
                    "reason": l.reason,
                    "created_at": l.created_at.isoformat() if l.created_at else "N/A"
                })
                if l.action in ["REJECTED", "RETURNED"] and l.reason:
                    rejection_reason = l.reason

        discount_threshold = tier.max_discount_pct if tier else 15.0
        required_route = "Sales Manager & Finance Approval Required" if quotation.requires_approval else "Automatic Approval (Low Risk)"

        # ── 5. DEAL HEALTH & NEGOTIATION ──────────────────────────────────────
        health_score = 85 if (deal and deal.risk == "low") else (60 if (deal and deal.risk == "medium") else 40)
        risk_indicators = []
        if quotation.margin_percentage < 15.0:
            risk_indicators.append(f"Low margin percentage: {quotation.margin_percentage}% (Target min: 15%)")
        if total_discount_pct > discount_threshold:
            risk_indicators.append(f"Discount {total_discount_pct}% exceeds tier threshold of {discount_threshold}%")

        quote_messages = db.query(QuoteMessage).filter(QuoteMessage.quotation_id == quotation.id).order_by(QuoteMessage.created_at.asc()).all()
        messages_data = [
            {"sender_type": m.sender_type, "content": m.content, "created_at": m.created_at.isoformat() if m.created_at else "N/A"}
            for m in quote_messages
        ]

        # ── 6. FULFILLMENT & STOCK ─────────────────────────────────────────────
        fulfillment_data = generate_fulfillment_plans(db, f"order-for-{quotation_id}")
        stock_details = []
        for line in quotation.lines:
            stocks = db.query(Stock).filter(Stock.product_id == line.product_id).all()
            for st in stocks:
                wh = db.query(Warehouse).filter(Warehouse.id == st.warehouse_id).first()
                stock_details.append({
                    "product_id": line.product_id,
                    "warehouse_name": wh.name if wh else st.warehouse_id,
                    "quantity_on_hand": st.quantity_on_hand,
                    "quantity_allocated": st.quantity_allocated,
                    "available": st.quantity_on_hand - st.quantity_allocated
                })

        # ── 7. SHIPPING (Shiprocket check) ────────────────────────────────────
        raw_rates = shipping_service.get_shipping_rates()
        is_shiprocket_available = any(
            isinstance(r, dict) and (r.get("adapter") == "Shiprocket" or r.get("courier") == "Shiprocket")
            for r in raw_rates
        ) if raw_rates else False

        if is_shiprocket_available:
            shipping_context = {
                "status": "Available",
                "is_live_shiprocket": True,
                "options": raw_rates
            }
        else:
            shipping_context = "Shipping data unavailable"

        context = {
            "customer": {
                "customer_id": customer.id if customer else "N/A",
                "name": customer.name if customer else (deal.customer_name if deal else "Customer"),
                "tier": tier.name if tier else "Standard",
                "loyalty_information": "Gold Tier VIP" if (tier and tier.name == "Gold") else "Standard Tier Customer",
                "account_creation_date": account_creation_date,
                "account_age_days": account_age_days,
                "lifetime_revenue": round(lifetime_revenue, 2),
                "purchase_count": purchase_count,
                "purchase_frequency": "Monthly Active" if purchase_count >= 3 else "Occasional",
                "average_order_value": round(avg_order_value, 2),
                "last_purchase_date": last_purchase_date,
                "historical_average_discount": historical_avg_discount,
                "historical_quotation_count": len(previous_quotes_summary),
                "historical_deal_count": len(previous_deals_summary),
                "previous_quotations": previous_quotes_summary[:5],
                "previous_deals": previous_deals_summary[:5],
                "previous_orders": previous_orders_summary[:5]
            },
            "subscriptions": {
                "active_subscriptions": subscriptions_data,
                "total_active": len(subscriptions_data)
            },
            "current_quotation": {
                "quotation_id": quotation.id,
                "quote_number": f"QUOTE-{quotation.id[:8].upper()}",
                "quotation_status": quotation.status,
                "quotation_date": quotation.created_at.isoformat() if quotation.created_at else "N/A",
                "customer_name": customer.name if customer else (deal.customer_name if deal else "Unknown"),
                "sales_representative": "Sales Rep",
                "quotation_currency": "INR",
                "quotation_lines": line_items,
                "subtotal": quotation.subtotal,
                "total_cost": total_cost,
                "total_discount": quotation.total_discount,
                "discount_percentage": total_discount_pct,
                "total_amount": quotation.total,
                "total_margin": total_margin,
                "margin_percentage": quotation.margin_percentage
            },
            "approval": {
                "approval_status": app_req.status if app_req else ("APPROVED" if not quotation.requires_approval else "PENDING"),
                "approval_steps": approval_logs_data,
                "current_approval_step": "Manager & Finance Review" if quotation.requires_approval else "Approved",
                "approver": "Sales Manager / Finance",
                "approval_reason": "Low Risk / Standard Criteria" if not quotation.requires_approval else "Manual Approval Required",
                "rejection_return_reason": rejection_reason,
                "discount_threshold": discount_threshold,
                "calculated_risk": quotation.risk_score,
                "required_approval_route": required_route
            },
            "deal_health": {
                "health_score": health_score,
                "health_status": "HEALTHY" if health_score >= 70 else "AT_RISK",
                "stalled_status": "Active (2 days in current stage)",
                "anomaly_information": "None detected",
                "delivery_promise_slippage": "None",
                "risk_indicators": risk_indicators or ["No high commercial risks detected"]
            },
            "negotiation": {
                "negotiation_status": deal.status if deal else "draft",
                "customer_change_requests": "None",
                "requested_discount_changes": f"Current quote discount is {total_discount_pct}%",
                "negotiation_messages": messages_data,
                "reapproval_triggered": quotation.requires_approval
            },
            "fulfillment": {
                "plans": fulfillment_data.get("plans", []),
                "available_stock": stock_details
            },
            "shipping": shipping_context
        }

        # Apply Company AI Data Privacy Filter from PostgreSQL
        return self.filter_context_by_company_config(db, context)

    def filter_context_by_company_config(self, db: Session, context: Dict[str, Any]) -> Dict[str, Any]:
        """
        Loads CompanyAIConfig from PostgreSQL and strips out any disabled data categories.
        """
        config = db.query(CompanyAIConfig).filter(CompanyAIConfig.id == "default-config").first()
        if not config:
            return context

        filtered = json.loads(json.dumps(context, default=json_serialize_default))

        # Customer filters
        if "customer" in filtered:
            c = filtered["customer"]
            if not config.share_customer_tier:
                c["tier"] = "[DATA_DISABLED_BY_COMPANY_POLICY]"
            if not config.share_loyalty_status:
                c["loyalty_information"] = "[DATA_DISABLED_BY_COMPANY_POLICY]"
            if not config.share_lifetime_revenue:
                c["lifetime_revenue"] = "[DATA_DISABLED_BY_COMPANY_POLICY]"
            if not config.share_purchase_count:
                c["purchase_count"] = "[DATA_DISABLED_BY_COMPANY_POLICY]"
            if not config.share_purchase_frequency:
                c["purchase_frequency"] = "[DATA_DISABLED_BY_COMPANY_POLICY]"
            if not config.share_avg_order_value:
                c["average_order_value"] = "[DATA_DISABLED_BY_COMPANY_POLICY]"
            if not config.share_historical_discounts:
                c["historical_average_discount"] = "[DATA_DISABLED_BY_COMPANY_POLICY]"

        # Subscriptions filters
        if not config.share_active_subscriptions and "subscriptions" in filtered:
            filtered["subscriptions"]["active_subscriptions"] = "[DATA_DISABLED_BY_COMPANY_POLICY]"

        # Deal filters
        if "deal_health" in filtered and not config.share_deal_health:
            filtered["deal_health"]["health_score"] = "[DATA_DISABLED_BY_COMPANY_POLICY]"

        # Fulfillment filters
        if not config.share_allocation_plans and "fulfillment" in filtered:
            filtered["fulfillment"]["plans"] = "[DATA_DISABLED_BY_COMPANY_POLICY]"

        # Shipping filters
        if not config.share_shipping_cost and "shipping" in filtered:
            filtered["shipping"] = "[DATA_DISABLED_BY_COMPANY_POLICY]"

        return filtered

    def generate_explanation(self, context: Dict[str, Any], role: str = "sales") -> Dict[str, Any]:
        """
        Generates dynamic AI explanation using real local Ollama.
        If Ollama is disabled, unreachable, or fails, raises HTTP 503 (service unavailable).
        If Ollama response cannot be parsed, raises HTTP 422 (unprocessable entity).
        NO static / fake AI fallback response is returned.
        """
        settings = get_settings()
        enabled = settings.AI_ENABLED and self.enabled
        base_url = (settings.AI_BASE_URL or self.base_url).rstrip('/')
        model = settings.AI_MODEL or self.model

        if not enabled:
            logger.warning("AI explanation requested but AI is disabled in configuration.")
            raise HTTPException(
                status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
                detail="AI explanation service is currently unavailable."
            )

        role_lower = role.lower()
        if "manager" in role_lower:
            perspective = "Sales Manager focus on discount compliance, risk score, margin protection, rep performance, and approval routing."
        elif "fin" in role_lower or "ops" in role_lower:
            perspective = "Finance and Operations focus on margin %, discount impact, shipping costs, warehouse split efficiency, and backorder risk."
        else:
            perspective = "Sales Representative focus on customer relationship, loyalty, active subscriptions, upsell/cross-sell, margin, and approval blockers."

        system_prompt = AI_SYSTEM_PROMPT_TEMPLATE.format(role_perspective=perspective)

        url = f"{base_url}/api/chat"
        payload = {
            "model": model,
            "messages": [
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": f"STRUCTURED CONTEXT FACTS:\n{json.dumps(context, indent=2, default=json_serialize_default)}"}
            ],
            "stream": False,
            "format": "json",
            "options": {
                "think": False
            }
        }

        start_time = datetime.now()
        logger.info(f"Initiating Ollama AI explanation request to {url} using model '{model}'")

        try:
            resp = requests.post(url, json=payload, timeout=90)
            duration_ms = (datetime.now() - start_time).total_seconds() * 1000
            logger.info(f"Ollama API response received in {duration_ms:.2f}ms with status HTTP {resp.status_code}")

            if resp.status_code != 200:
                logger.error(f"Ollama returned HTTP error {resp.status_code}: {resp.text[:300]}")
                raise HTTPException(
                    status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
                    detail="AI explanation service is currently unavailable."
                )

            result = resp.json()
            msg_content = result.get("message", {}).get("content", "")
            if not msg_content:
                logger.error("Ollama response contained empty message content.")
                raise HTTPException(
                    status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
                    detail="AI service returned an empty response."
                )

            parsed = json.loads(msg_content)
            parsed["ai_status"] = "live_ollama"
            parsed["advisory_notice"] = "AI insights are advisory. DealFlow360 business rules and backend calculations are authoritative."
            return parsed

        except HTTPException:
            raise
        except json.JSONDecodeError as exc:
            logger.error(f"Failed to parse structured JSON from Ollama response: {exc}")
            raise HTTPException(
                status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
                detail="Failed to parse structured AI response."
            )
        except Exception as exc:
            logger.error(f"Ollama communication failure: {exc}")
            raise HTTPException(
                status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
                detail="AI explanation service is currently unavailable."
            )

    def build_warehouse_ai_context(self, db: Session, order_id: str) -> Dict[str, Any]:
        """
        Loads authoritative warehouse stock, allocation plans, and shipping estimates for order fulfillment.
        """
        plans_data = generate_fulfillment_plans(db, order_id)
        shipping_options = shipping_service.get_shipping_rates()

        context = {
            "order_id": order_id,
            "required_quantity": plans_data.get("required_quantity", 10),
            "plans": plans_data.get("plans", []),
            "shipping_options": shipping_options
        }
        return self.filter_context_by_company_config(db, context)

    def generate_warehouse_explanation(self, context: Dict[str, Any], role: str = "finance") -> Dict[str, Any]:
        """
        Generates AI warehouse split recommendations using real Ollama.
        Raises 503/422 if Ollama fails.
        """
        settings = get_settings()
        enabled = settings.AI_ENABLED and self.enabled
        base_url = (settings.AI_BASE_URL or self.base_url).rstrip('/')
        model = settings.AI_MODEL or self.model

        if not enabled:
            raise HTTPException(
                status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
                detail="AI explanation service is currently unavailable."
            )

        url = f"{base_url}/api/chat"
        payload = {
            "model": model,
            "messages": [
                {"role": "system", "content": WAREHOUSE_SYSTEM_PROMPT_TEMPLATE},
                {"role": "user", "content": f"STRUCTURED WAREHOUSE & FULFILLMENT FACTS:\n{json.dumps(context, indent=2, default=json_serialize_default)}"}
            ],
            "stream": False,
            "format": "json",
            "options": {
                "think": False
            }
        }

        try:
            resp = requests.post(url, json=payload, timeout=90)
            if resp.status_code != 200:
                raise HTTPException(
                    status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
                    detail="AI explanation service is currently unavailable."
                )

            result = resp.json()
            msg_content = result.get("message", {}).get("content", "")
            if not msg_content:
                raise HTTPException(
                    status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
                    detail="AI service returned an empty response."
                )

            parsed = json.loads(msg_content)
            parsed["ai_status"] = "live_ollama"
            return parsed

        except HTTPException:
            raise
        except Exception as exc:
            logger.error(f"Warehouse AI explanation failure: {exc}")
            raise HTTPException(
                status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
                detail="AI explanation service is currently unavailable."
            )

ai_service = AIService()
