"""add_warehouse_crud_stock_pdf_sync

Revision ID: 0efbe9ac4a4d
Revises: 39e62d340e6f
Create Date: 2026-09-06 02:25:20.667015+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0efbe9ac4a4d'
down_revision: Union[str, Sequence[str], None] = '39e62d340e6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer_tiers', sa.Column('min_spend', sa.Float(), nullable=True))
    op.add_column('customer_tiers', sa.Column('max_discount_pct', sa.Float(), nullable=True))
    op.drop_column('customer_tiers', 'baseline_discount')
    op.drop_column('customer_tiers', 'updated_at')
    op.drop_column('customer_tiers', 'is_active')
    op.add_column('customers', sa.Column('tier_id', sa.String(), nullable=True))
    op.alter_column('customers', 'company',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_foreign_key(None, 'customers', 'customer_tiers', ['tier_id'], ['id'])
    op.drop_column('customers', 'tier')
    op.alter_column('deals', 'customer_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('discount_policies', sa.Column('target_category', sa.String(), nullable=True))
    op.drop_column('discount_policies', 'product_category')
    op.drop_column('discount_policies', 'employee_role')
    op.alter_column('invoice_lines', 'product_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('invoice_lines', 'unit_price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('invoice_lines', 'amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('invoices', 'order_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('invoices', 'customer_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('invoices', 'subtotal',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('invoices', 'total_discount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('invoices', 'tax',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('invoices', 'total',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('invoices', 'amount_paid',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=True)
    op.add_column('orders', sa.Column('tracking_number', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('carrier', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('estimated_delivery', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('delivery_notes', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('payments', 'amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('products', 'sales_price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('products', 'cost',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('quotations', 'subtotal',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('quotations', 'total_discount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('quotations', 'total',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('quotations', 'margin_percentage',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('quote_lines', 'unit_price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('quote_lines', 'discount_percent',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.Float(),
               existing_nullable=True)
    op.add_column('stock', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('subscriptions', sa.Column('plan_id', sa.String(), nullable=True))
    op.add_column('subscriptions', sa.Column('start_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('subscriptions', sa.Column('end_date', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('subscriptions', 'order_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('subscriptions', 'product_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('subscriptions', 'price_per_period',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               nullable=True)
    op.create_foreign_key(None, 'subscriptions', 'subscription_plans', ['plan_id'], ['id'])
    op.add_column('warehouses', sa.Column('code', sa.String(), nullable=True))
    op.add_column('warehouses', sa.Column('pincode', sa.String(), nullable=True))
    op.add_column('warehouses', sa.Column('address', sa.String(), nullable=True))
    op.add_column('warehouses', sa.Column('city', sa.String(), nullable=True))
    op.add_column('warehouses', sa.Column('state', sa.String(), nullable=True))
    op.add_column('warehouses', sa.Column('country', sa.String(), nullable=True))
    op.add_column('warehouses', sa.Column('capacity', sa.Integer(), nullable=True))
    op.add_column('warehouses', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('warehouses', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('warehouses', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_warehouses_code'), 'warehouses', ['code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_warehouses_code'), table_name='warehouses')
    op.drop_column('warehouses', 'updated_at')
    op.drop_column('warehouses', 'created_at')
    op.drop_column('warehouses', 'is_active')
    op.drop_column('warehouses', 'capacity')
    op.drop_column('warehouses', 'country')
    op.drop_column('warehouses', 'state')
    op.drop_column('warehouses', 'city')
    op.drop_column('warehouses', 'address')
    op.drop_column('warehouses', 'pincode')
    op.drop_column('warehouses', 'code')
    op.drop_constraint(None, 'subscriptions', type_='foreignkey')
    op.alter_column('subscriptions', 'price_per_period',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
    op.alter_column('subscriptions', 'product_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('subscriptions', 'order_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('subscriptions', 'end_date')
    op.drop_column('subscriptions', 'start_date')
    op.drop_column('subscriptions', 'plan_id')
    op.drop_column('stock', 'updated_at')
    op.alter_column('quote_lines', 'discount_percent',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=5, scale=2),
               existing_nullable=True)
    op.alter_column('quote_lines', 'unit_price',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)
    op.alter_column('quotations', 'margin_percentage',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=5, scale=2),
               existing_nullable=True)
    op.alter_column('quotations', 'total',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True)
    op.alter_column('quotations', 'total_discount',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True)
    op.alter_column('quotations', 'subtotal',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True)
    op.alter_column('products', 'cost',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)
    op.alter_column('products', 'sales_price',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)
    op.alter_column('payments', 'amount',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)
    op.drop_column('orders', 'updated_at')
    op.drop_column('orders', 'delivery_notes')
    op.drop_column('orders', 'estimated_delivery')
    op.drop_column('orders', 'carrier')
    op.drop_column('orders', 'tracking_number')
    op.alter_column('invoices', 'amount_paid',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True)
    op.alter_column('invoices', 'total',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True)
    op.alter_column('invoices', 'tax',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True)
    op.alter_column('invoices', 'total_discount',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True)
    op.alter_column('invoices', 'subtotal',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True)
    op.alter_column('invoices', 'customer_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('invoices', 'order_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('invoice_lines', 'amount',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)
    op.alter_column('invoice_lines', 'unit_price',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)
    op.alter_column('invoice_lines', 'product_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('discount_policies', sa.Column('employee_role', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('discount_policies', sa.Column('product_category', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('discount_policies', 'target_category')
    op.alter_column('deals', 'customer_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('customers', sa.Column('tier', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'customers', type_='foreignkey')
    op.alter_column('customers', 'company',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('customers', 'tier_id')
    op.add_column('customer_tiers', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('customer_tiers', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('customer_tiers', sa.Column('baseline_discount', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True))
    op.drop_column('customer_tiers', 'max_discount_pct')
    op.drop_column('customer_tiers', 'min_spend')
    # ### end Alembic commands ###

