"""update_admin_rules

Revision ID: 39e62d340e6f
Revises: 31176cd6a2e7
Create Date: 2026-09-06 00:04:08.665854+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '39e62d340e6f'
down_revision: Union[str, None] = '31176cd6a2e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_approval_rules_id'), table_name='approval_rules')
    op.drop_table('approval_rules')
    op.drop_index(op.f('ix_pricing_rules_id'), table_name='pricing_rules')
    op.drop_table('pricing_rules')
    op.drop_index(op.f('ix_approval_chains_id'), table_name='approval_chains')
    op.drop_table('approval_chains')
    op.add_column('discount_policies', sa.Column('product_category', sa.String(), nullable=True))
    op.add_column('discount_policies', sa.Column('employee_role', sa.String(), nullable=True))
    op.drop_column('discount_policies', 'target_category')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('discount_policies', sa.Column('target_category', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('discount_policies', 'employee_role')
    op.drop_column('discount_policies', 'product_category')
    op.create_table('approval_chains',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('sequence', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('approval_chains_pkey'))
    )
    op.create_index(op.f('ix_approval_chains_id'), 'approval_chains', ['id'], unique=False)
    op.create_table('pricing_rules',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('target_role', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('max_discount_percent', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=False),
    sa.Column('requires_approval_above', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pricing_rules_pkey'))
    )
    op.create_index(op.f('ix_pricing_rules_id'), 'pricing_rules', ['id'], unique=False)
    op.create_table('approval_rules',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('risk_threshold', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('discount_threshold', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('target_role', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('approval_rules_pkey'))
    )
    op.create_index(op.f('ix_approval_rules_id'), 'approval_rules', ['id'], unique=False)
    # ### end Alembic commands ###
