// Customer Portal Mock Data

import {
  Quotation,
  Order,
  Invoice,
  Subscription,
} from "./types";

export const mockQuotations: Quotation[] = [
  {
    id: "q1",
    quotationNumber: "QT-2026-0041",
    title: "Enterprise Infrastructure Bundle",
    status: "negotiating",
    lineItems: [
      {
        id: "li1",
        productName: "Dell PowerEdge Server (R740)",
        productType: "hardware",
        qty: 10,
        unitPrice: 50000,
        discount: 5,
        finalPrice: 47500,
      },
      {
        id: "li2",
        productName: "Rack Installation Service",
        productType: "service",
        qty: 1,
        unitPrice: 10000,
        discount: 0,
        finalPrice: 10000,
      },
      {
        id: "li3",
        productName: "Cloud Backup Subscription",
        productType: "subscription",
        qty: 1,
        unitPrice: 2000,
        discount: 5,
        finalPrice: 1900,
        isRecurring: true,
        billingCycle: "monthly",
      },
    ],
    subtotal: 515000,
    totalDiscount: 26000,
    grandTotal: 489000,
    validUntil: "2026-09-30",
    createdAt: "2026-09-01",
    salesRep: "Rajesh Kumar",
    negotiationRequests: [
      {
        id: "nr1",
        lineItemId: "li1",
        type: "price",
        requestedPrice: 45000,
        message: "We are ordering 10 units and would like a volume discount.",
        status: "pending",
        createdAt: "2026-09-03T10:30:00",
      },
    ],
    notes:
      "Pricing valid for Q3 2026. Includes standard warranty. Installation to be scheduled within 30 days of delivery.",
  },
  {
    id: "q2",
    quotationNumber: "QT-2026-0038",
    title: "Office 365 Migration Package",
    status: "sent",
    lineItems: [
      {
        id: "li4",
        productName: "Microsoft 365 Business Premium",
        productType: "subscription",
        qty: 50,
        unitPrice: 1800,
        discount: 10,
        finalPrice: 1620,
        isRecurring: true,
        billingCycle: "monthly",
      },
      {
        id: "li5",
        productName: "Migration Consulting (per day)",
        productType: "service",
        qty: 5,
        unitPrice: 15000,
        discount: 0,
        finalPrice: 15000,
      },
    ],
    subtotal: 165000,
    totalDiscount: 9000,
    grandTotal: 156000,
    validUntil: "2026-09-20",
    createdAt: "2026-08-28",
    salesRep: "Priya Sharma",
    negotiationRequests: [],
  },
  {
    id: "q3",
    quotationNumber: "QT-2026-0035",
    title: "Network Security Upgrade",
    status: "approved",
    lineItems: [
      {
        id: "li6",
        productName: "Cisco Firewall (ASA 5506-X)",
        productType: "hardware",
        qty: 2,
        unitPrice: 85000,
        discount: 8,
        finalPrice: 78200,
      },
      {
        id: "li7",
        productName: "Security Audit & Setup",
        productType: "service",
        qty: 1,
        unitPrice: 25000,
        discount: 0,
        finalPrice: 25000,
      },
    ],
    subtotal: 195000,
    totalDiscount: 13600,
    grandTotal: 181400,
    validUntil: "2026-10-01",
    createdAt: "2026-08-20",
    salesRep: "Amit Singh",
    negotiationRequests: [],
  },
];

export const mockOrders: Order[] = [
  {
    id: "o1",
    orderNumber: "ORD-2026-0018",
    quotationId: "q3",
    title: "Network Security Upgrade",
    status: "partially_shipped",
    total: 181400,
    placedAt: "2026-08-25",
    estimatedDelivery: "2026-09-10",
    hasSubscription: false,
    fulfillments: [
      {
        warehouseName: "Mumbai Central WH",
        items: ["Cisco Firewall (ASA 5506-X) x2"],
        status: "shipped",
        trackingNumber: "DTDC-9823741",
        estimatedDelivery: "2026-09-08",
      },
      {
        warehouseName: "Pune Tech WH",
        items: ["Security Audit & Setup"],
        status: "pending",
        estimatedDelivery: "2026-09-12",
      },
    ],
  },
  {
    id: "o2",
    orderNumber: "ORD-2026-0012",
    quotationId: "q-prev",
    title: "Developer Workstations Q2",
    status: "delivered",
    total: 340000,
    placedAt: "2026-07-10",
    hasSubscription: true,
    fulfillments: [
      {
        warehouseName: "Delhi North WH",
        items: ["Dell XPS 15 x4", "HP 27\" Monitor x4"],
        status: "delivered",
        trackingNumber: "BLUEDART-5512893",
        estimatedDelivery: "2026-07-18",
      },
    ],
  },
];

export const mockInvoices: Invoice[] = [
  {
    id: "inv1",
    invoiceNumber: "INV-2026-0055",
    orderId: "o2",
    description: "Developer Workstations Q2 — Final Invoice",
    status: "paid",
    amount: 340000,
    dueDate: "2026-07-25",
    issuedAt: "2026-07-18",
    paidAt: "2026-07-22",
  },
  {
    id: "inv2",
    invoiceNumber: "INV-2026-0061",
    orderId: "o1",
    description: "Network Security Upgrade — Advance (50%)",
    status: "paid",
    amount: 90700,
    dueDate: "2026-08-30",
    issuedAt: "2026-08-25",
    paidAt: "2026-08-27",
  },
  {
    id: "inv3",
    invoiceNumber: "INV-2026-0068",
    orderId: "o1",
    description: "Network Security Upgrade — Balance (50%)",
    status: "sent",
    amount: 90700,
    dueDate: "2026-09-15",
    issuedAt: "2026-09-05",
  },
  {
    id: "inv4",
    invoiceNumber: "INV-2026-0071",
    description: "Cloud Backup Subscription — September",
    status: "sent",
    amount: 1900,
    dueDate: "2026-09-10",
    issuedAt: "2026-09-01",
    isProratedOrCreditNote: false,
  },
  {
    id: "inv5",
    invoiceNumber: "CN-2026-0004",
    description: "Credit Note — Early cancellation adjustment",
    status: "void",
    amount: -5000,
    dueDate: "2026-08-01",
    issuedAt: "2026-07-30",
    isProratedOrCreditNote: true,
  },
];

export const mockSubscriptions: Subscription[] = [
  {
    id: "sub1",
    productName: "Cloud Backup",
    plan: "Business 5TB",
    status: "active",
    billingCycle: "monthly",
    amount: 1900,
    nextBillingDate: "2026-10-01",
    startDate: "2026-06-01",
    usagePercent: 62,
  },
  {
    id: "sub2",
    productName: "Microsoft 365 Business Premium",
    plan: "50 Seats",
    status: "trial",
    billingCycle: "monthly",
    amount: 1620,
    nextBillingDate: "2026-09-20",
    startDate: "2026-08-20",
    usagePercent: 78,
  },
  {
    id: "sub3",
    productName: "CRM Pro (Zoho)",
    plan: "Enterprise",
    status: "cancelled",
    billingCycle: "annual",
    amount: 45000,
    nextBillingDate: "—",
    startDate: "2025-01-01",
    cancelledAt: "2026-07-15",
  },
];
